import type { ContextCard } from "@/lib/sources/types";

const now = Date.now();
const hours = (value: number) => value * 60 * 60 * 1000;

export const inboxMockCards: ContextCard[] = [
	{
		id: "linear-hel-184",
		source: "linear",
		externalId: "HEL-184",
		externalUrl: "https://linear.app/helmor/issue/HEL-184",
		title: "Tighten Codex session resume path",
		subtitle: "Helmor Core",
		state: { label: "Started", tone: "open" },
		lastActivityAt: now - hours(1.4),
		meta: {
			type: "linear",
			identifier: "HEL-184",
			priorityLabel: "High",
			team: { name: "Core", key: "HEL" },
			project: { name: "Agent runtime", color: "#5E6AD2" },
			labels: [
				{ name: "runtime", color: "#5E6AD2" },
				{ name: "ux", color: "#26B5CE" },
			],
		},
	},
	{
		id: "linear-hel-197",
		source: "linear",
		externalId: "HEL-197",
		externalUrl: "https://linear.app/helmor/issue/HEL-197",
		title: "Inbox cards should preserve source context",
		subtitle: "Helmor Product",
		state: { label: "Backlog", tone: "neutral" },
		lastActivityAt: now - hours(7),
		meta: {
			type: "linear",
			identifier: "HEL-197",
			priorityLabel: "Medium",
			team: { name: "Product", key: "HEL" },
			project: { name: "Kanban inbox", color: "#F2C94C" },
			labels: [{ name: "design", color: "#F2994A" }],
		},
	},
	{
		id: "github-pr-helmor-428",
		source: "github_pr",
		externalId: "helmor/desktop#428",
		externalUrl: "https://github.com/helmor/desktop/pull/428",
		title: "Add workspace status sync for forge events",
		subtitle: "helmor/desktop",
		state: { label: "Review", tone: "open" },
		lastActivityAt: now - hours(2.2),
		meta: {
			type: "github_pr",
			repo: "helmor/desktop",
			number: 428,
			additions: 482,
			deletions: 91,
			changedFiles: 14,
			ciStatus: "pending",
		},
	},
	{
		id: "github-issue-helmor-391",
		source: "github_issue",
		externalId: "helmor/desktop#391",
		externalUrl: "https://github.com/helmor/desktop/issues/391",
		title: "Kanban drag preview jumps at the final frame",
		subtitle: "helmor/desktop",
		state: { label: "Open", tone: "urgent" },
		lastActivityAt: now - hours(12),
		meta: {
			type: "github_issue",
			repo: "helmor/desktop",
			number: 391,
			labels: [
				{ name: "bug", color: "#D73A4A" },
				{ name: "frontend", color: "#A2EEEF" },
			],
		},
	},
	{
		id: "github-discussion-helmor-54",
		source: "github_discussion",
		externalId: "helmor/desktop#54",
		externalUrl: "https://github.com/helmor/desktop/discussions/54",
		title: "How should prepared backlog drafts reopen?",
		subtitle: "helmor/desktop · Discussions",
		state: { label: "Unanswered", tone: "unanswered" },
		lastActivityAt: now - hours(28),
		meta: {
			type: "github_discussion",
			repo: "helmor/desktop",
			number: 54,
			category: { name: "Q&A", emoji: "?" },
		},
	},
	{
		id: "slack-thread-eng-182",
		source: "slack_thread",
		externalId: "engineering/182.44",
		externalUrl: "https://slack.com/app_redirect?channel=engineering",
		title: "Release train needs a cleaner branch handoff",
		subtitle: "#engineering",
		state: { label: "Thread", tone: "neutral" },
		lastActivityAt: now - hours(3.5),
		meta: {
			type: "slack_thread",
			workspaceName: "Helmor",
			channelName: "#engineering",
			rootAuthor: { name: "Mira" },
		},
	},
];
